/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocomunicacao.core;

import java.awt.Dialog.ModalExclusionType;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import projetocomunicacao.fachada.FachadaCliente;
import projetocomunicacao.rede.Cliente;
import projetocomunicacao.udp.ModuloEspecial;

/**
 *
 * @author Guilherme
 */
public class TelaInicial extends javax.swing.JFrame {
    protected String name_sala_dialog;
    public TelaInicial ti;
    private Cliente cliente;
    private FachadaCliente fachada;
    private Game gui;
    private DesenhaGUI desenha;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() throws IOException {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegrasDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sairregras_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SalaDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        criarsala_button = new javax.swing.JButton();
        nomesala_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GroupDialog = new javax.swing.JDialog();
        group_panel = new javax.swing.JPanel();
        groupicon = new javax.swing.JLabel();
        completa = new javax.swing.JLabel();
        escolha = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        group_background = new javax.swing.JLabel();
        ServerDialog = new javax.swing.JDialog();
        server_panel = new javax.swing.JPanel();
        serverlabel1 = new javax.swing.JLabel();
        serverlabel2 = new javax.swing.JLabel();
        serverlabel3 = new javax.swing.JLabel();
        OKServer = new javax.swing.JButton();
        server_background = new javax.swing.JLabel();
        EspecialDialogInicial = new javax.swing.JDialog();
        especial_panel = new javax.swing.JPanel();
        alterar_label = new javax.swing.JLabel();
        confirm_number = new javax.swing.JButton();
        textfield_especial = new javax.swing.JTextField();
        especial_background = new javax.swing.JLabel();
        RoomDialog = new javax.swing.JDialog();
        room_panel = new javax.swing.JPanel();
        room_icon = new javax.swing.JLabel();
        selecionada = new javax.swing.JLabel();
        escolha_room = new javax.swing.JLabel();
        OK_room = new javax.swing.JButton();
        room_background = new javax.swing.JLabel();
        panel_inicial = new javax.swing.JPanel();
        logoInicial = new javax.swing.JLabel();
        salas = new javax.swing.JLabel();
        nick = new javax.swing.JLabel();
        ip_textfield = new javax.swing.JTextField();
        dupla_combobox = new javax.swing.JComboBox();
        criarjogo_button = new javax.swing.JButton();
        ip = new javax.swing.JLabel();
        regras_button = new javax.swing.JButton();
        salas_scrollpane = new javax.swing.JScrollPane();
        salas_list = new javax.swing.JList();
        criarnovasala_button = new javax.swing.JButton();
        dupla = new javax.swing.JLabel();
        nick_textfield = new javax.swing.JTextField();
        conectar = new javax.swing.JButton();
        especial_button = new javax.swing.JButton();
        inicial_background = new javax.swing.JLabel();

        RegrasDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        RegrasDialog.setTitle("Regras do Jogo");
        RegrasDialog.setMinimumSize(new java.awt.Dimension(500, 500));
        RegrasDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        RegrasDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        RegrasDialog.setResizable(false);

        jPanel2.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Regras do Jogo");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1. 4 participantes, duas duplas com participantes alternados (ABAB), cada jogador");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("recebe 6 pedras.");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("2. Na primeira jogada da partida, começa quem tiver a carroça de maior valor.");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("3. Em sentido horário, o próximo jogador coloca uma pedra com o valor igual a");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("da pedra que está em uma das pontas. Caso não possua, passa a vez.");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("4. Ganha a rodada da partida quem acabar primeiro com as pedras da mão.");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("permanecer empatado, a rodada é cancelada.");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("6. Pontuação:");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("    Se a pedra serviu em apenas uma das pontas e não é carroça, 1 ponto.");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("    Se a pedra serviu em apenas uma das pontas e é carroça, 2 pontos.");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("    Se a pedra serviu em ambas pontas e não é uma carroça, 3 pontos.");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("    Se a pedra serviu em ambas pontas e é uma carroça, 4 pontos.");

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("7. Ganha o jogo quem primeiro obtiver 7 pontos primeiro. ");

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("*carroça: pedra com valores iguais nas duas pontas.");

        sairregras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_sairregras_closed.png"))); // NOI18N
        sairregras_button.setBorderPainted(false);
        sairregras_button.setContentAreaFilled(false);
        sairregras_button.setDefaultCapable(false);
        sairregras_button.setFocusPainted(false);
        sairregras_button.setFocusable(false);
        sairregras_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairregras_buttonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairregras_buttonMouseEntered(evt);
            }
        });
        sairregras_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairregras_buttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("5. Em caso de empate, ganha quem tiver menos pontos agregados. Em caso de");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(sairregras_button)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(2, 2, 2)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(sairregras_button)
                .addContainerGap())
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_load.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel7.setMinimumSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout RegrasDialogLayout = new javax.swing.GroupLayout(RegrasDialog.getContentPane());
        RegrasDialog.getContentPane().setLayout(RegrasDialogLayout);
        RegrasDialogLayout.setHorizontalGroup(
            RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        RegrasDialogLayout.setVerticalGroup(
            RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegrasDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        SalaDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SalaDialog.setTitle("Nome da Sala");
        SalaDialog.setMinimumSize(new java.awt.Dimension(350, 170));
        SalaDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        SalaDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        SalaDialog.setResizable(false);
        SalaDialog.getContentPane().setLayout(null);

        jPanel4.setOpaque(false);

        criarsala_button.setFont(new java.awt.Font("Verdana", 0, 14));
        criarsala_button.setForeground(new java.awt.Color(255, 255, 255));
        criarsala_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_check_criarsala.png"))); // NOI18N
        criarsala_button.setText("Criar!");
        criarsala_button.setBorderPainted(false);
        criarsala_button.setContentAreaFilled(false);
        criarsala_button.setDefaultCapable(false);
        criarsala_button.setFocusPainted(false);
        criarsala_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarsala_buttonActionPerformed(evt);
            }
        });

        nomesala_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomesala_textfieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome da Sala");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(criarsala_button))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomesala_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomesala_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarsala_button)
                .addGap(30, 30, 30))
        );

        SalaDialog.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_load.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(350, 170));
        jLabel4.setMinimumSize(new java.awt.Dimension(350, 170));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(350, 170));
        SalaDialog.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 350, 170);

        GroupDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        GroupDialog.setTitle("Dupla cheia");
        GroupDialog.setLocationByPlatform(true);
        GroupDialog.setMinimumSize(new java.awt.Dimension(400, 175));
        GroupDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        GroupDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        GroupDialog.setResizable(false);
        GroupDialog.getContentPane().setLayout(null);

        group_panel.setMinimumSize(new java.awt.Dimension(400, 175));
        group_panel.setOpaque(false);
        group_panel.setLayout(null);

        groupicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/groupFull64.png"))); // NOI18N
        group_panel.add(groupicon);
        groupicon.setBounds(310, 20, 90, 90);

        completa.setFont(new java.awt.Font("Verdana", 0, 18));
        completa.setText("A dupla escolhida está completa!");
        completa.setToolTipText("");
        group_panel.add(completa);
        completa.setBounds(10, 11, 296, 23);

        escolha.setFont(new java.awt.Font("Verdana", 0, 18));
        escolha.setText("Escolha outra dupla.");
        escolha.setToolTipText("");
        group_panel.add(escolha);
        escolha.setBounds(10, 35, 183, 23);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        group_panel.add(OK);
        OK.setBounds(310, 110, 70, 23);

        group_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_disconnection.jpg"))); // NOI18N
        group_panel.add(group_background);
        group_background.setBounds(0, 0, 400, 210);

        GroupDialog.getContentPane().add(group_panel);
        group_panel.setBounds(0, 0, 400, 160);

        ServerDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ServerDialog.setTitle("Servidor não encontrado");
        ServerDialog.setLocationByPlatform(true);
        ServerDialog.setMinimumSize(new java.awt.Dimension(400, 175));
        ServerDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        ServerDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        ServerDialog.setResizable(false);
        ServerDialog.getContentPane().setLayout(null);

        server_panel.setMinimumSize(new java.awt.Dimension(400, 175));
        server_panel.setOpaque(false);
        server_panel.setLayout(null);

        serverlabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_disconnection.png"))); // NOI18N
        server_panel.add(serverlabel1);
        serverlabel1.setBounds(10, 30, 120, 120);

        serverlabel2.setFont(new java.awt.Font("Verdana", 0, 18));
        serverlabel2.setText("Falha ao se conectar com o servidor!");
        server_panel.add(serverlabel2);
        serverlabel2.setBounds(30, 10, 333, 18);

        serverlabel3.setFont(new java.awt.Font("Verdana", 0, 18));
        serverlabel3.setText("IP ou formato inválido");
        server_panel.add(serverlabel3);
        serverlabel3.setBounds(160, 30, 201, 23);

        OKServer.setText("OK");
        OKServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKServerActionPerformed(evt);
            }
        });
        server_panel.add(OKServer);
        OKServer.setBounds(290, 120, 73, 23);

        server_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_disconnection.jpg"))); // NOI18N
        server_panel.add(server_background);
        server_background.setBounds(0, 0, 400, 160);

        ServerDialog.getContentPane().add(server_panel);
        server_panel.setBounds(0, 0, 400, 175);

        EspecialDialogInicial.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        EspecialDialogInicial.setTitle("Módulo Especial");
        EspecialDialogInicial.setLocationByPlatform(true);
        EspecialDialogInicial.setMinimumSize(new java.awt.Dimension(400, 150));
        EspecialDialogInicial.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        EspecialDialogInicial.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        EspecialDialogInicial.setResizable(false);
        EspecialDialogInicial.getContentPane().setLayout(null);

        especial_panel.setMinimumSize(new java.awt.Dimension(400, 175));
        especial_panel.setOpaque(false);

        alterar_label.setFont(new java.awt.Font("Verdana", 0, 18));
        alterar_label.setForeground(new java.awt.Color(255, 255, 255));
        alterar_label.setText("Alterar número do módulo especial:");
        alterar_label.setToolTipText("");

        confirm_number.setText("Confirmar");
        confirm_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_numberActionPerformed(evt);
            }
        });

        textfield_especial.setText("0");

        javax.swing.GroupLayout especial_panelLayout = new javax.swing.GroupLayout(especial_panel);
        especial_panel.setLayout(especial_panelLayout);
        especial_panelLayout.setHorizontalGroup(
            especial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(especial_panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(especial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(especial_panelLayout.createSequentialGroup()
                        .addComponent(textfield_especial, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm_number))
                    .addComponent(alterar_label, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        especial_panelLayout.setVerticalGroup(
            especial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(especial_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(alterar_label)
                .addGap(18, 18, 18)
                .addGroup(especial_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textfield_especial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        EspecialDialogInicial.getContentPane().add(especial_panel);
        especial_panel.setBounds(0, 0, 400, 150);

        especial_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/woodenBackgroundSmall.png"))); // NOI18N
        EspecialDialogInicial.getContentPane().add(especial_background);
        especial_background.setBounds(0, 1, 400, 150);

        RoomDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        RoomDialog.setTitle("Nenhuma sala selecionada");
        RoomDialog.setLocationByPlatform(true);
        RoomDialog.setMinimumSize(new java.awt.Dimension(400, 175));
        RoomDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        RoomDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        RoomDialog.setResizable(false);
        RoomDialog.getContentPane().setLayout(null);

        room_panel.setMinimumSize(new java.awt.Dimension(400, 175));
        room_panel.setOpaque(false);
        room_panel.setLayout(null);

        room_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/choose_room64.png"))); // NOI18N
        room_panel.add(room_icon);
        room_icon.setBounds(310, 20, 90, 90);

        selecionada.setFont(new java.awt.Font("Verdana", 0, 18));
        selecionada.setText("Nenhuma sala foi selecionada!");
        selecionada.setToolTipText("");
        room_panel.add(selecionada);
        selecionada.setBounds(10, 11, 274, 23);

        escolha_room.setFont(new java.awt.Font("Verdana", 0, 18));
        escolha_room.setText("Escolha uma sala.");
        escolha_room.setToolTipText("");
        room_panel.add(escolha_room);
        escolha_room.setBounds(10, 35, 162, 23);

        OK_room.setText("OK");
        OK_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_roomActionPerformed(evt);
            }
        });
        room_panel.add(OK_room);
        OK_room.setBounds(310, 110, 70, 23);

        room_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_disconnection.jpg"))); // NOI18N
        room_panel.add(room_background);
        room_background.setBounds(0, 0, 400, 210);

        RoomDialog.getContentPane().add(room_panel);
        room_panel.setBounds(0, 0, 400, 160);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início - DominoMania");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panel_inicial.setOpaque(false);
        panel_inicial.setLayout(null);

        logoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/logo_transparente_modificada.png"))); // NOI18N
        panel_inicial.add(logoInicial);
        logoInicial.setBounds(0, 0, 300, 300);

        salas.setFont(new java.awt.Font("Verdana", 0, 24));
        salas.setForeground(new java.awt.Color(96, 67, 12));
        salas.setText("Salas Disponíveis");
        panel_inicial.add(salas);
        salas.setBounds(460, 110, 220, 40);

        nick.setFont(new java.awt.Font("Verdana", 0, 24));
        nick.setForeground(new java.awt.Color(96, 67, 12));
        nick.setText("Nickname:");
        nick.setToolTipText("");
        panel_inicial.add(nick);
        nick.setBounds(70, 290, 130, 40);

        ip_textfield.setToolTipText("");
        ip_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_textfieldActionPerformed(evt);
            }
        });
        panel_inicial.add(ip_textfield);
        ip_textfield.setBounds(270, 400, 110, 30);

        dupla_combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dupla 1", "Dupla 2" }));
        panel_inicial.add(dupla_combobox);
        dupla_combobox.setBounds(210, 350, 70, 30);

        criarjogo_button.setFont(new java.awt.Font("Verdana", 0, 12));
        criarjogo_button.setForeground(new java.awt.Color(96, 67, 12));
        criarjogo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_dado.png"))); // NOI18N
        criarjogo_button.setText("Jogar!");
        criarjogo_button.setDefaultCapable(false);
        criarjogo_button.setEnabled(false);
        criarjogo_button.setFocusPainted(false);
        criarjogo_button.setFocusable(false);
        criarjogo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarjogo_buttonActionPerformed(evt);
            }
        });
        panel_inicial.add(criarjogo_button);
        criarjogo_button.setBounds(290, 440, 160, 70);

        ip.setFont(new java.awt.Font("Verdana", 0, 24));
        ip.setForeground(new java.awt.Color(96, 67, 12));
        ip.setText("IP do Servidor:");
        panel_inicial.add(ip);
        ip.setBounds(70, 390, 190, 40);

        regras_button.setFont(new java.awt.Font("Verdana", 0, 14));
        regras_button.setForeground(new java.awt.Color(96, 67, 12));
        regras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_interrogacao.png"))); // NOI18N
        regras_button.setText("Regras");
        regras_button.setBorderPainted(false);
        regras_button.setContentAreaFilled(false);
        regras_button.setFocusPainted(false);
        regras_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regras_buttonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regras_buttonMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regras_buttonMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                regras_buttonMouseReleased(evt);
            }
        });
        regras_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regras_buttonActionPerformed(evt);
            }
        });
        panel_inicial.add(regras_button);
        regras_button.setBounds(50, 470, 140, 50);

        salas_scrollpane.setViewportView(salas_list);

        panel_inicial.add(salas_scrollpane);
        salas_scrollpane.setBounds(460, 160, 250, 270);

        criarnovasala_button.setFont(new java.awt.Font("Verdana", 0, 11));
        criarnovasala_button.setForeground(new java.awt.Color(96, 67, 12));
        criarnovasala_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_button_criarsala.png"))); // NOI18N
        criarnovasala_button.setText("Criar Nova Sala");
        criarnovasala_button.setEnabled(false);
        criarnovasala_button.setFocusPainted(false);
        criarnovasala_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarnovasala_buttonActionPerformed(evt);
            }
        });
        panel_inicial.add(criarnovasala_button);
        criarnovasala_button.setBounds(460, 440, 250, 70);

        dupla.setFont(new java.awt.Font("Verdana", 0, 24));
        dupla.setForeground(new java.awt.Color(96, 67, 12));
        dupla.setText("Dupla:");
        dupla.setToolTipText("");
        panel_inicial.add(dupla);
        dupla.setBounds(70, 340, 90, 40);

        nick_textfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nick_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nick_textfieldActionPerformed(evt);
            }
        });
        panel_inicial.add(nick_textfield);
        nick_textfield.setBounds(210, 300, 220, 30);

        conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_check_criarsala.png"))); // NOI18N
        conectar.setBorder(null);
        conectar.setBorderPainted(false);
        conectar.setContentAreaFilled(false);
        conectar.setFocusPainted(false);
        conectar.setFocusable(false);
        conectar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/glowing_icon_check32.png"))); // NOI18N
        conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarActionPerformed(evt);
            }
        });
        panel_inicial.add(conectar);
        conectar.setBounds(390, 400, 50, 30);

        especial_button.setFont(new java.awt.Font("Verdana", 0, 14));
        especial_button.setForeground(new java.awt.Color(96, 67, 12));
        especial_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_especial.png"))); // NOI18N
        especial_button.setText("Especial");
        especial_button.setBorderPainted(false);
        especial_button.setContentAreaFilled(false);
        especial_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        especial_button.setFocusPainted(false);
        especial_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_especial_glow.png"))); // NOI18N
        especial_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                especial_buttonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                especial_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                especial_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                especial_buttonMouseExited(evt);
            }
        });
        especial_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especial_buttonActionPerformed(evt);
            }
        });
        panel_inicial.add(especial_button);
        especial_button.setBounds(50, 430, 150, 40);

        inicial_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_telainicial.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(inicial_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(inicial_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ip_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_textfieldActionPerformed

    private void criarjogo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarjogo_buttonActionPerformed
        // TODO add your handling code here:
	 if(salas_list.getSelectedIndex() < 0) {
	    RoomDialog.setLocationRelativeTo(panel_inicial);
	    RoomDialog.setModal(false);
	    RoomDialog.setVisible(true);
	 } else{
	    if(!this.fachada.podeAdicionar(dupla_combobox.getSelectedIndex(),salas_list.getSelectedIndex())) {
		GroupDialog.setLocationRelativeTo(null);
		GroupDialog.setVisible(true);
		GroupDialog.setModal(true);
		return;
	    }
	    this.desenha = new DesenhaGUI(fachada, gui);
	    this.desenha.start();
	    this.fachada.adicionaJogador(nick_textfield.getText(), dupla_combobox.getSelectedIndex(), salas_list.getSelectedIndex());
	    gui.setVisible(true);
	    this.setVisible(false);
	 }
    }//GEN-LAST:event_criarjogo_buttonActionPerformed

    private void regras_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regras_buttonActionPerformed
        // TODO add your handling code here:
	RegrasDialog.setLocationRelativeTo(panel_inicial);
        RegrasDialog.setVisible(true);
        RegrasDialog.setModal(true);
    }//GEN-LAST:event_regras_buttonActionPerformed

    private void criarnovasala_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarnovasala_buttonActionPerformed
        // TODO add your handling code here
         int tam = this.fachada.mostraSalas().size();
         this.fachada.criaSala(tam);
       
    }//GEN-LAST:event_criarnovasala_buttonActionPerformed

    private void nomesala_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomesala_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomesala_textfieldActionPerformed

    private void criarsala_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarsala_buttonActionPerformed
        // TODO add your handling code here:
        name_sala_dialog = nomesala_textfield.getText();
        nomesala_textfield.setText("");
        SalaDialog.setVisible(false);
    }//GEN-LAST:event_criarsala_buttonActionPerformed

    private void sairregras_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairregras_buttonActionPerformed
        // TODO add your handling code here:
        RegrasDialog.setVisible(false);
    }//GEN-LAST:event_sairregras_buttonActionPerformed

    private void sairregras_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairregras_buttonMouseEntered
        // TODO add your handling code here:
        sairregras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_sairregras_open.png")));
    }//GEN-LAST:event_sairregras_buttonMouseEntered

    private void sairregras_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairregras_buttonMouseExited
        // TODO add your handling code here:
        sairregras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_sairregras_closed.png")));
    }//GEN-LAST:event_sairregras_buttonMouseExited

    private void regras_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regras_buttonMouseEntered
        // TODO add your handling code here:
        regras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_exclamacao.png")));
    }//GEN-LAST:event_regras_buttonMouseEntered

    private void regras_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regras_buttonMouseReleased
    }//GEN-LAST:event_regras_buttonMouseReleased

    private void regras_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regras_buttonMouseExited
        // TODO add your handling code here:
        regras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/icon_interrogacao.png")));
    }//GEN-LAST:event_regras_buttonMouseExited

    private void regras_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regras_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regras_buttonMouseClicked

    private void nick_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nick_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nick_textfieldActionPerformed

    private void conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarActionPerformed
        // TODO add your handling code here:
	//checar aqui se o endereço é válido, talvez
	if (ip_textfield.getText().length() > 0){
            try {
                this.cliente = new Cliente(this.ip_textfield.getText()); 
                this.fachada = new FachadaCliente(cliente);
                this.gui = new Game(fachada,this);
                EscreveNomeSalas ens = new EscreveNomeSalas(this, fachada);
                ens.start();
                this.gui.setLocationRelativeTo(null);
               
                try{
                    InputStream imgStream = this.gui.getClass().getResourceAsStream("/projetocomunicacao/resources/logotransparente2.png");
                    BufferedImage bi = ImageIO.read(imgStream);
                    ImageIcon myImg = new ImageIcon(bi);
                    gui.setIconImage(myImg.getImage());
                } catch(Exception e){
                    System.out.println(e);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
	    conectar.setEnabled(false);
	    criarjogo_button.setEnabled(true);
	    criarnovasala_button.setEnabled(true);
	}
	
	else {
	    ServerDialog.setLocationRelativeTo(panel_inicial);
	    ServerDialog.setVisible(true);
	    ServerDialog.setModal(true);
	}
    }//GEN-LAST:event_conectarActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        GroupDialog.setVisible(false);
        GroupDialog.setModal(false);
    }//GEN-LAST:event_OKActionPerformed

    private void OKServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKServerActionPerformed
        // TODO add your handling code here:
	ServerDialog.setVisible(false);
	ServerDialog.setModal(false);
    }//GEN-LAST:event_OKServerActionPerformed

    private void confirm_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_numberActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(textfield_especial.getText().trim());
        ModuloEspecial.setNumero(num);
        EspecialDialogInicial.setVisible(false);
        EspecialDialogInicial.setModal(false);
    }//GEN-LAST:event_confirm_numberActionPerformed

    private void OK_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_roomActionPerformed
        // TODO add your handling code here:
        RoomDialog.setVisible(false);
        RoomDialog.setModal(false);
    }//GEN-LAST:event_OK_roomActionPerformed

    private void especial_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especial_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_especial_buttonMouseClicked

    private void especial_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especial_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_especial_buttonMouseEntered

    private void especial_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especial_buttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_especial_buttonMouseExited

    private void especial_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especial_buttonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_especial_buttonMouseReleased

    private void especial_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especial_buttonActionPerformed
        // TODO add your handling code here:
        EspecialDialogInicial.setLocationRelativeTo(panel_inicial);
        EspecialDialogInicial.setVisible(true);
        EspecialDialogInicial.setModal(false);
    }//GEN-LAST:event_especial_buttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    TelaInicial ti = new TelaInicial();
                    ti.setVisible(false);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog EspecialDialogInicial;
    private javax.swing.JDialog GroupDialog;
    private javax.swing.JButton OK;
    private javax.swing.JButton OKServer;
    private javax.swing.JButton OK_room;
    private javax.swing.JDialog RegrasDialog;
    private javax.swing.JDialog RoomDialog;
    private javax.swing.JDialog SalaDialog;
    private javax.swing.JDialog ServerDialog;
    private javax.swing.JLabel alterar_label;
    private javax.swing.JLabel completa;
    private javax.swing.JButton conectar;
    private javax.swing.JButton confirm_number;
    private javax.swing.JButton criarjogo_button;
    private javax.swing.JButton criarnovasala_button;
    private javax.swing.JButton criarsala_button;
    private javax.swing.JLabel dupla;
    private javax.swing.JComboBox dupla_combobox;
    private javax.swing.JLabel escolha;
    private javax.swing.JLabel escolha_room;
    private javax.swing.JLabel especial_background;
    private javax.swing.JButton especial_button;
    private javax.swing.JPanel especial_panel;
    private javax.swing.JLabel group_background;
    private javax.swing.JPanel group_panel;
    private javax.swing.JLabel groupicon;
    private javax.swing.JLabel inicial_background;
    private javax.swing.JLabel ip;
    private javax.swing.JTextField ip_textfield;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logoInicial;
    private javax.swing.JLabel nick;
    private javax.swing.JTextField nick_textfield;
    private javax.swing.JTextField nomesala_textfield;
    private javax.swing.JPanel panel_inicial;
    private javax.swing.JButton regras_button;
    private javax.swing.JLabel room_background;
    private javax.swing.JLabel room_icon;
    private javax.swing.JPanel room_panel;
    private javax.swing.JButton sairregras_button;
    private javax.swing.JLabel salas;
    protected javax.swing.JList salas_list;
    private javax.swing.JScrollPane salas_scrollpane;
    private javax.swing.JLabel selecionada;
    private javax.swing.JLabel server_background;
    private javax.swing.JPanel server_panel;
    private javax.swing.JLabel serverlabel1;
    private javax.swing.JLabel serverlabel2;
    private javax.swing.JLabel serverlabel3;
    private javax.swing.JTextField textfield_especial;
    // End of variables declaration//GEN-END:variables
}
