/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetocomunicacao.core;

/**
 *
 * @author Vinícius
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public WelcomeFrame() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        load_panel = new javax.swing.JPanel();
        loading = new javax.swing.JLabel();
        grupo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        load_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Loading DominoMania...");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        load_panel.setMinimumSize(new java.awt.Dimension(400, 175));
        load_panel.setOpaque(false);

        loading.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setText("     Loading...");

        grupo.setForeground(new java.awt.Color(255, 255, 255));
        grupo.setText("© dcms2 - gpp - lapl - mmfrb - vmrc");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/logo_transparente_modificada.png"))); // NOI18N

        javax.swing.GroupLayout load_panelLayout = new javax.swing.GroupLayout(load_panel);
        load_panel.setLayout(load_panelLayout);
        load_panelLayout.setHorizontalGroup(
            load_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(load_panelLayout.createSequentialGroup()
                .addGroup(load_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(load_panelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(logo))
                    .addGroup(load_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(load_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grupo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        load_panelLayout.setVerticalGroup(
            load_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(load_panelLayout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(load_panel);
        load_panel.setBounds(0, 0, 410, 380);

        load_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetocomunicacao/resources/background_load.jpg"))); // NOI18N
        getContentPane().add(load_background);
        load_background.setBounds(0, 1, 410, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new WelcomeFrame().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grupo;
    private javax.swing.JLabel load_background;
    private javax.swing.JPanel load_panel;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
